<?php
/**
 * @file Contains code for NicaFileObject.
 */

namespace Drupal\nica_migrate\Plugin\migrate;

use Drupal\migrate_source_csv\CSVFileObject;

class NicaFileObject extends CSVFileObject {

  /**
   * @inheritdoc
   */
  public function current() {
    $row =  parent::current(); // TODO: Change the autogenerated stub

    if ($row && !empty($this->columnNames)) {
      for ($i = 1 ; $i < 5; $i++) {
        $row['material'][] = $row["material$i"];
        unset($row["material$i"]);
      }
      $row['material_id'] = implode('', $row['material']);
    }
    return $row;
  }

}
