<?php

/**
 * @file
 * Contains nica_custom.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */


function nica_custom_theme() {
  return [
    'nica_custom_cv' => [
      'variables' => [
        'nica_entity' => NULL,
      ],
    ],
  ];

}

/**
 * Implements hook_help().
 */
function nica_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nica_custom module.
    case 'help.page.nica_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modulo Nica Custom') . '</p>';
      return $output;

    default:
  }
  
}
